version: '3'

services:
    avail_gpi:
        name: avail_gpi
        build: ./avail_gpi
        volumes:
            - ./avail_gpi/:/app
            - /var/log/:/app/logs

    controller:
        name: av_manager
        build: ./controller
        volumes:
            - ./controller/:/app
            - /Projects/avail_gpi_0.8_docker/avail_gpi/cfg/:/app/cfg
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/log:/app/logs